version: "3"

services:
  nodejs:
    image: nodejs
    restart: on-failure
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: npm run server

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "33000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - "8080:80"